### ISSUE TITLE
Example Client

### ISSUE THREAD

**Issue by Throvn** [tm-drtina/signal-provisioning-api#1]
Good evening,
I just stumbled accross this project and it seems awesome.
However I would need some more guidance on this project and 
I think an example Client would help me out a lot.

Are there any updates on the way?
Thank you in advance!
Louis

**Comment by tm-drtina** [comment]
Hi, sorry for the late reply.

I've tested my client implementation and it stopped working. I've tried updating to newest libsignal-client, but that didn't help 😞 
There had to be some change in API, because the same code worked earlier and now returns `409 Conflict`
I remember this was an issue with version/user agent. Hopefully I'll fix it in the following weeks and after that I'll publish the implementation.

**Comment by tm-drtina** [comment]
The issue was that my client didn't specify capabilities that server expected 🤦‍♂️ 

You can check the client implementation here: https://github.com/tm-drtina/signal-dbus-client
Since the it is very crude I won't be linking it in Readme just yet.

**Comment by Throvn** [comment]
Omg, you are the best haha!
